services:
  message-broker:
    restart: always
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  users_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: please
      POSTGRES_PASSWORD: hireMe

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: superSecret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: superSecret
      ME_CONFIG_MONGODB_URL: mongodb://root:superSecret@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  rabbitmq_data:
    driver: local
  pg_data:
    driver: local
